### ISSUE TITLE
Timezone butler is posting multiple messages when someone mentions a time. 

### ISSUE THREAD

**Issue by chrisbrookins** [mathieudutour/timezone-butler#50] opened 2021-04-20 21:18 UTC
**Describe the bug**
Timezone butler is showing posting 3 times every time someone mentions a time.  Why?

**To Reproduce**
1. Go to our slack channel
2. Post a message with a time
3. See something like this https://a.cl.ly/6qu8vAZp

**Expected behavior**
One message should be posted, not 3

**Screenshots**
https://a.cl.ly/6qu8vAZp

**Additional context**

**Comment by stephen-apto** [comment] 2021-05-18 17:40
we are also experiencing this. any thoughts @mathieudutour ?

**Comment by bionboy** [comment] 2022-11-30 19:26
@mathieudutour Mark as duplicate of https://github.com/mathieudutour/timezone-butler/issues/46 pls

**Comment by mathieudutour** [comment] 2022-12-01 08:45
duplicate of #46

**Closed by mathieudutour** 2022-12-01 08:45 UTC
Labels: bug
