### ISSUE TITLE
Timezone Butler responds 3-4 times 

### ISSUE THREAD

**Issue by stevecoccia** [mathieudutour/timezone-butler#76] opened 2022-07-26 13:24 UTC
**Describe the bug**
When someone mentions a time (i.e 3pm) Timezone Butler will respond 3 or 4 times with (i.e "3pm is 8pm in your timezone")
**To Reproduce**
1. In any slack channel say a time
2. Notice Timezone Butler responds more than once

**Expected behavior**
I would expect a single respond

**Screenshots**

<img width="750" alt="Screen Shot 2022-07-26 at 9 23 37 AM" src="https://user-images.githubusercontent.com/16547322/181016535-71da553f-ea46-48d5-9577-f3ebeb0fb055.png">

**Comment by bwjohnson-ss** [comment] 2022-08-15 16:27
I'm seeing this same issue, and it's a show stopper for my team, since it's very distracting.

**Comment by rwardnavex** [comment] 2022-09-23 20:58
Our team has been getting creative about how to write times so Butler won't pick them up to avoid this super annoying behavior.

**Comment by mathieudutour** [comment] 2022-10-03 09:47
> Our team has been getting creative about how to write times so Butler won't pick them up

Could you explain what you are doing to avoid it?

**Comment by bionboy** [comment] 2022-11-30 19:27
@mathieudutour Mark as duplicate of https://github.com/mathieudutour/timezone-butler/issues/46 pls

**Comment by mathieudutour** [comment] 2022-12-01 08:44
duplicate of #46

**Closed by mathieudutour** 2022-12-01 08:44 UTC
Labels: bug
