### ISSUE TITLE
Too many messages

### ISSUE THREAD

**Issue by chandlervdw** [mathieudutour/timezone-butler#75] opened 2022-07-05 19:43 UTC
**The app posts 4 messages**
When posting a time, the app responds 4 times with your current timezone instead of once.

**To Reproduce**
1. Just post a message with a time.

**Expected behavior**
There should be one response from the app.

**Screenshots**
<img width="309" alt="Screen Shot 2022-07-05 at 12 04 43 PM" src="https://user-images.githubusercontent.com/332278/177402737-1f07c123-2172-4997-a825-a942835e3f3b.png">

**Comment by glenda-tn** [comment] 2022-07-06 19:28
This is happening to me too. Is it because I added the app as an individual while my colleague added it to our public slack channels and therefore it is duplicated?

**Comment by bionboy** [comment] 2022-11-30 19:27
@mathieudutour Mark as duplicate of https://github.com/mathieudutour/timezone-butler/issues/46 pls

**Comment by mathieudutour** [comment] 2022-12-01 08:44
duplicate of #46

**Closed by mathieudutour** 2022-12-01 08:44 UTC
Labels: bug
