### ISSUE TITLE
The Butler is sending repeated messages

### ISSUE THREAD

**Issue by richard-wood** [mathieudutour/timezone-butler#54] opened 2021-05-20 14:16 UTC
**Describe the bug**
When I post a message with a time in my colleague receives the timezone message multiple times 

**To Reproduce**
1. install the app
2. invite to the channel
3. uninstall the app
4. reinstall the app
5. remove and re-invite the app to a channel
6. say "meeting at 09z"
7. the timezone butler will post two messages for the timezone the meetings are in.

**Expected behaviour**
I was hoping to only receive the message once, not multiple times

**Screenshots**
<img width="301" alt="Screenshot 2021-05-20 at 15 15 30" src="https://user-images.githubusercontent.com/2256455/118994512-4fc10600-b97e-11eb-810e-fe2f7c63add6.png">

**Additional context**
I have no additional context

**Comment by bionboy** [comment] 2022-11-30 19:21
I am seeing this behavior when only installing, and then inviting to a channel once. I have noticed double posts but my peer has informed me they have seen it post 3 duplicate messages at times.

**Comment by bionboy** [comment] 2022-11-30 19:27
@mathieudutour Mark as duplicate of https://github.com/mathieudutour/timezone-butler/issues/46 pls

**Comment by mathieudutour** [comment] 2022-12-01 08:44
duplicate of #46

**Closed by mathieudutour** 2022-12-01 08:44 UTC
Labels: bug
